### ISSUE TITLE
Having difficulty running shell script

### ISSUE THREAD

**Issue by lmdavidson** [OHNLP/MedXN#1]
I am trying to run the shell script given on my mac terminal, and I get an error--

Error: Could not find or load main class org.apache.uima.tools.cvd.CVD
Caused by: java.lang.ClassNotFoundException: org.apache.uima.tools.cvd.CVD

Any idea what I need to do to fix this? Thank you in advance.

**Comment by qqndrew** [comment]
Typically this is caused by missing dependencies. While there is a plan to eventually convert this to maven in an IDE agnostic manner, for the time being please make sure the JARs in the /lib folder are in the classpath by modifying the shell scrip and adding lib/ to the argument for -cp

**Comment by qqndrew** [comment]
As an addendum, what is in the repository here is merely the source code, and does not contain the compiled MedXN Binary. You will need to compile first or download the binary directly from https://sourceforge.net/projects/ohnlp/files/MedXN/1.0.1/MedXN-1.0.1.zip/download

**Comment by lmdavidson** [comment]
Thank you for the quick reply, Andrew 

I was able to run it successfully and forgot to respond back. I can run both the CPE and CVD.
