### ISSUE TITLE
Unable to run shell script?

### ISSUE THREAD

**Issue by suchaaver-chahal** [OHNLP/MedXN#2]
I know this title is exactly like the previous closed issue, but I think the Mavenization has occurred and so the lib stuff has been removed. The README seems to be out of date. What steps should I take to run this properly?

**EDIT** I checked out to the commit before the mavenization and was able to run it, but I have to admit that I'm a little green here. I'm interested in using this tool to extract information regarding frequency (e.g. Take 1 tablet twice daily), from a string extracted from prescription data on the label of a bottle. However, I'm unfamiliar with the analysis engines and other stuff it wants me to load. Is there somewhere I can read to better understand how to use this tool? I intended to start by reading the Apache UIMA tooling.

**Comment by ymnliu** [comment]
@suchaaver-chahal Can you check if the dist branch works for your purpose? Additional instructions are provided in the updated README.md.

**Comment by qqndrew** [comment]
Should be fixed as of v1.0.3 , please try downloading the zip from latest release https://github.com/OHNLP/MedXN/releases/tag/v1.0.3

Will close this issue, please open new issue if the downloadable zip does not work for some reason.
