### ISSUE TITLE
Run CPE via command line without GUI

### ISSUE THREAD

**Issue by vishaldeyiiest** [OHNLP/MedXN#4]
When we run the run "runMedXNCPE.sh", it opens a GUI frame. But I was wondering if there is a way to run collection processing engine (CPE) without the GUI. In essence, I want to run CPE from terminal by running some shell script/java code.
I do not want the GUI because I would like to run MedXN in server machines with large input files.

Is there any way to run MedXN without GUI from terminal?

**Comment by qqndrew** [comment]
This is possible directly via java.
What you want to do is some variant of the following for the default pipeline
```java
CollectionReaderDescription cr= CollectionReaderFactory.createReaderDescription(FileSystemReader.class, "InputDirectory", "path/to/your/input/dir");
AggregateBuilder pipeline = new AggregateBuilder();
pipeline.add(AnalysisEngineFactory.createEngineDescription("medxndesc.aggregate_analysis_engine.MedXNAggregateTAE"));
pipeline.add(YourAnnotationConsumerHere, "OutputFile", "your/output/file.ext"); // "org.ohnlp.medxn.ccs.MedXNCC" for default
SimplePipeline.runPipeline(cr, pipeline.createAggregateDescription());
```

**Comment by qqndrew** [comment]
Worth noting, you may wish to substitute the CollectionReader with one of your own implementation (refer to UIMA documentation) to, as an example, read in data directly via JDBC or somesuch if you are working with large files and don't want to dump separately into a flatfile somewhere.
