### ISSUE TITLE
git checkout in readme fails

### ISSUE THREAD

**Issue by tmills** [OHNLP/MedXN#5]
I get the error:
```
> git checkout dist
fatal: 'dist' could be both a local file and a tracking branch.
Please use -- (and optionally --no-guess) to disambiguate
```

if I give a more specific command:
```> git co remotes/origin/dist```

then I am able to proceed with the ant download command.

**Comment by qqndrew** [comment]
Thanks for bringing this to our attention. We have deleted the dist branch which should resolve this disambiguation issue.
