### ISSUE TITLE
ant download_medtagger issue

### ISSUE THREAD

**Issue by zilion22** [OHNLP/MedXN#6]
1) The project location is at https://github.com/OHNLP/MedTagger
and at the URL stated in the README

2) MedXN]$ ant download_medtagger
Buildfile: /home/ec2-user/SageMaker/LEV_FOLDER/MedXN/build.xml

BUILD FAILED
Target "download_medtagger" does not exist in the project "MedXN Build".

**Comment by qqndrew** [comment]
Seems the build instructions fell out of sync with our updated pipelines and need to be updated.
Please give the proposed [updated instructions](https://github.com/OHNLP/MedXN/blob/integrations/backbone/README.md) a try and create a new issue if you still encounter issues.

Note that depending on your use case you may not need to recompile from scratch, and just downloading the release zip may be sufficient.
