### ISSUE TITLE
Need backbone version 1.0.6

### ISSUE THREAD

**Issue by pnavitha** [OHNLP/MedXN#9]
I have followed the readme instructions but mvn clean install failled. Then we explicitly added jar file of MedTagger(1.0.13) and Backbone (1.0.4).  Still facing issue with following error:

"MedXN/src/main/java/org/ohnlp/medxn/backbone/MedXNOutputToOHDSIFormatTransform.java:[3,34] package com.fasterxml.jackson.core does not exist"

Only thing fixed it was changing Backbone version (1.0.6). Kindly check the root issue.

**Comment by qqndrew** [comment]
Thanks for the heads up, this should have been fixed as of MedXN v1.0.4.

Backbone v1.0.6 is correct.

Please feel free to reopen the issue if you are still experiencing problems.
